cardiometabolic <- c(
  "Hypertension",
  "Diabetes",
  "Venous thromboembolic disease (Excl PE)",
  "Supraventricular tachycardia",
  "Pulmonary embolism",
  "Atrial fibrillation",
  "Stable angina",
  "Fatty Liver",
  "Coronary heart disease not otherwise specified",
  "Transient ischaemic attack",
  "Glomerulonephritis",
  "Right bundle branch block",
  "Alcoholic liver disease",
  "Unstable Angina",
  "Acute Kidney Injury",
  "Congenital malformations of cardiac septa",
  "Liver fibrosis, sclerosis and cirrhosis",
  "Diabetic ophthalmic complications",
  "Intracranial hypertension",
  "Hepatic failure",
  "Left bundle branch block",
  "Multiple valve dz",
  "Nonrheumatic mitral valve disorders",
  "Subarachnoid haemorrhage",
  "Myocardial infarction",
  "Nonrheumatic aortic valve disorders",
  "Atrioventricular block, first degree",
  "End stage renal disease",
  "Heart failure",
  "Ischaemic stroke",
  "Stroke NOS",
  "Intracerebral haemorrhage",
  "Atrioventricular block, second degree",
  "Other Cardiomyopathy",
  "Peripheral arterial disease",
  "Abdominal aortic aneurysm",
  "Dilated cardiomyopathy",
  "Portal hypertension",
  "Rheumatic valve dz",
  "Atrioventricular block, complete",
  "Autoimmune liver disease",
  "Bifascicular block",
  "Diabetic neurological complications",
  "Hypertrophic Cardiomyopathy",
  "Primary pulmonary hypertension",
  "Secondary pulmonary hypertension",
  "Trifascicular block",
  "Ventricular tachycardia"
)
